### PR TITLE
First version of schema support

### LINKED ISSUE #20: Schemas support
Does helmi support custom parameters using OSB schemas? If not, is it on the road map at the moment?

### PR DESCRIPTION
**Pull request by hkroger**
Fixes #20

### CODE REVIEW

**Comment by hkroger** [comment]
Currently this always outputs schema even if it is empty. Schema looks like this:

```          
          "schemas": {
            "service_instance": {
              "create": {
                "parameters": {}
              },
              "update": {
                "parameters": {}
              }
            },
            "service_binding": {
              "create": {
                "parameters": {}
              }
            }
          }
```

Is this ok according to the spec?

**Comment by hkroger** [comment]
@adrianliechti any comments on this?

**Comment by adrianliechti** [comment]
hey hey. i was unsure if you are already finished and happy with the result because of the „first version...“

so just wanted to wait and let you any time
:) i really like your extensions - and it seems we already have a usage and benefit of them... so thank you super much.

if you‘re happy with this (and i assume that now), i will review and merge.

**Comment by hkroger** [comment]
I think you can review and merge it now and if we need to extend and improve it some way later, we can do that. But it should already do the job  :)

**Comment by adrianliechti** [comment]
your wish is my order. thank you super much for this!

**Pull request merged**
