### PR TITLE
Use go-client, remove kubectl

### PR DESCRIPTION
**Pull request by adrianliechti**
goal: remove ~/.kube/config dependency on in-cluster-deplyoments

have a look at pkg/kubectl/kubectl.go

- remove kubectl process spawn
- use local config (~/.kube/config or rest credentials in /var/run...)
- add huge kubernetes client via (unsupported) dep  :/

rougly tested locally with docker-for-mac

### CODE REVIEW

**Comment by wdxxs2z** [comment]
Hi , @adrianliechti 

Maybe can import ( _ "k8s.io/client-go/plugin/pkg/client/auth" ), if user want to use oidc or other auth method. And the depend packages (github.com/Azure/go-autorest)  version may use v9.8.1.

**Comment by adrianliechti** [comment]
:)

thank you super much for your interest in helmi!

i will update the readme with a short-term roadmap.
your ideas absolutely makes sense.

as you see, there is also a pull request from sebastian to use a propper service broker sdk

another focus point is to ease the catalog file with a better/real template engine - and maybe split it into multiple files per service

cheers

**Comment by gandro** [comment]
@wdxxs2z Any reason you specifically need go-autorest v9.8.1?

It looks like dep would pull in v10 (which seems semver incompatible) due to our lack of version pinning.

**Comment by wdxxs2z** [comment]
Hi @gandro , the "github.com/Azure/go-autorest" version update soon, and the "client - go/plugins/pkg/client/auth/azure/azure.go" on some types , such as token part, haven't had time to make changes, so can only use relatively new v9 version.

**Comment by gandro** [comment]
@wdxxs2z I enabled the auth plugin and imported the pinned versions from go-client v7.0.0. This means that we are now using go-autorest v9.9.0. Does this solve your problem?

**Pull request merged**
