### PR TITLE
manual & empty init

### PR DESCRIPTION
**Pull request by adrianliechti**

### CODE REVIEW

**Comment by hkroger** [comment]
Looks good

**Comment by kazz-s** [comment]
I could use the new docker image, can we proceed?

**Comment by kazz-s** [comment]
Thx.

Could you also publish new docker image?

**Comment by kazz-s** [comment]
You forgot to set permissions:
kubectl logs helmi-5c8b84cd85-czj56
2019/06/08 14:29:41 failed to update repository datapipelines: Error: open /home/helmi/.helm/repository/repositories.yaml: permission denied

**Comment by adrianliechti** [comment]
ciao @kazz-s,

you were right about the permission :/ sorry for that.
does the current image on docker hub works for you (~2 days ago)? if so, I would create a new tag

**Comment by kazz-s** [comment]
Hey!
Sorry for the late response.
We are getting closer :D, but now In case no REPOSITORY_URLS will be provided helm update fails with:
`2019/06/12 18:22:03 Error: no repositories found. You must add one before updating`

**Comment by adrianliechti** [comment]
yeah babysteps by babysteps :)

do you think this is an exception? i'm not sure if an empty repository is desirable - except if you want to use local chart folders in the docker file...

we could send change the fatal/shutdown to a warning maybe...

**Comment by kazz-s** [comment]
Yes. I'm doing this in CI pipeline, I just mount volumes. Later I'm using chartmuseum.
How about "if helm list then helm update"?

**Comment by adrianliechti** [comment]
yes that could make sense
$ helm repo list

if the list is not empty, we will update
(even for helm itself this would be nice...)

**Comment by adrianliechti** [comment]
i pushed new images... let's see :) haha

$docker run -v $(pwd)/catalog:/app/catalog  --rm helmi
2019/06/13 00:54:11 Helmi is ready and available on port 5000

**Comment by kazz-s** [comment]
LGTM

**Comment by kazz-s** [comment]
please let me know when new static tag will be available.

**Comment by Flask** [comment]
Hey @kazz-s 
I've just tagged the current stable as 20190613.0 (monostream/helmi:20190613.0).

**Comment by kazz-s** [comment]
Thanks a lot. You can close the issue I raised.

**Pull request merged**
